server:
  port: 8761

spring:
  security:
    basic:
      enabled: false
      path: /**

eureka:
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000
    peerNodeConnectionIdleTimeoutSeconds: 5
    renewalThresholdUpdateIntervalMs: 10000
    peerEurekaStatusRefreshTimeIntervalMs: 10000
    peerEurekaNodesUpdateIntervalMs: 10000
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: ${DISCOVERY_HOST:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false